//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XocTuHr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_authors : DbContext
    {
        public db_authors()
            : base("name=DB_A7206A_mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_test> app_test { get; set; }
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<img> img { get; set; }
        public virtual DbSet<jobs> jobs { get; set; }
        public virtual DbSet<pub_info> pub_info { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<stores> stores { get; set; }
        public virtual DbSet<titleauthor> titleauthor { get; set; }
        public virtual DbSet<titles> titles { get; set; }
        public virtual DbSet<authors2> authors2 { get; set; }
        public virtual DbSet<authors3> authors3 { get; set; }
        public virtual DbSet<discounts> discounts { get; set; }
        public virtual DbSet<roysched> roysched { get; set; }
        public virtual DbSet<t1> t1 { get; set; }
        public virtual DbSet<titles2> titles2 { get; set; }
    }
}
